//Установление даних 
localStorage.setItem('lvlGodsIslands', 0)
localStorage.setItem('lvlGods', 0)
localStorage.setItem('GodHP', 300)
localStorage.setItem('countKillGods', 0)
localStorage.setItem('currentLevel', 0)
// localStorage.setItem('numberOfClicks', 0)
// localStorage.setItem('levelsCompleted', 0)
localStorage.setItem('totalCoins', 0)
// localStorage.setItem('totalKills', 0)
localStorage.setItem('totalExperience', 0)
localStorage.setItem('totalBossesKilled', 0)
localStorage.setItem('clickDamage', 1)
localStorage.setItem('priceGreece', 0)
localStorage.setItem('priceScandinavia', 20000)
localStorage.setItem('priceEgypt', 150000)
localStorage.setItem('lvlLocation', 1)
// localStorage.setItem('mythologyGreece', "true")
// localStorage.setItem('mythologyScandinavia', 'false')
// localStorage.setItem('mythologyEgypt', 'false')